### ISSUE TITLE
cooldown pulse

### ISSUE THREAD

**Issue by twin2** [greven/LumUI#1]
Hi!

Cooldownpulse is not working for my demonhunter, its only eyebeam i noticed so far being weird.

Sometimes it shows the icon even if it's off cooldown. but mostly its just not showing anything at all.

I noticed that demonhunter is not in the thresholdByClass list. 

Let me know if there is anything i can do to help troubleshoot.

Thanks !

/Nin

**Comment by greven** [comment]
Will look into this. Thanks for creating the issue.

**Comment by greven** [comment]
Fixed in the next release. :)
