### ISSUE TITLE
actionbar taint in instances

### ISSUE THREAD

**Issue by wjrogers** [greven/LumUI#3]
I'm using a GitHub clone @ fae3afd1ab47ed5422adf0ec63eece1562378087. I get this error every few seconds while in a dungeon:

```
280x LumUI\elements\actionbar.lua:90: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `GetEffectiveAlpha'
[string "@LumUI\elements\actionbar.lua"]:90: in function <LumUI\elements\actionbar.lua:88>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCooldown'
[string "@FrameXML\Cooldown.lua"]:5: in function `CooldownFrame_Set'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:616: in function `func'
[string "@FrameXML\AuraUtil.lua"]:43: in function <FrameXML\AuraUtil.lua:38>
[string "@FrameXML\AuraUtil.lua"]:58: in function `ForEachAura'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:597: in function `UpdateBuffs'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:209: in function `OnUnitAuraUpdate'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:65: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
```

config.lua:
```lua
-- Mods
C.settings.combatText = false
C.settings.tweaks = false

-- Elements
C.settings.cooldownsCount = false

-- move quest tracker to the right edge (not using those side action bars)
C.settings.minimap.questTrackerPosX = 0
```

**Comment by greven** [comment]
Thanks, haven't yet played an instance in this expansion as I'm still getting to 60, but I will look into it, thanks for the report.

**Comment by greven** [comment]
Hi, would you mind testing with the latest commit (https://github.com/greven/LumUI/commit/1bcd048a494b38b39590c8b758ee238f77dd9fc1) ?

Thanks. 👍 

Will test too once I run a dungeon.

**Comment by wjrogers** [comment]
That fixed it, thanks! Found another, much less frequent one that I'll open a new issue for.

**Comment by greven** [comment]
I'm using the wold rActionBars for LumUI but it hasn't been updated in ages.
It kinda needs me to pick it up and re-write it, but been avoiding doing that, but will have to eventually or this small issues will pick up.

Will mark this as closed and will release this soon. :)

Thanks again.

Nuno.
